### ISSUE TITLE
Error when run from command line

### ISSUE THREAD

**Issue by kalanda** [falconeta/capacitor-wifi-connect#12]
First of all, thanks a lot for this awesome project 😄

I'm having issues when I try to run my project in Android from the command line (not when I run it from Android Studio). The reason because I'm doing this is because is the only way I know is able to run the project with live reload in my device.

I run this command:
```
ionic capacitor run android -l --external
```

I'm getting this error:
```
...
[capacitor]         FAILURE: Build failed with an exception.
[capacitor]         
[capacitor]         * What went wrong:
[capacitor]         Execution failed for task ':falconeta-capacitor-wifi-connect:compileDebugKotlin'.
[capacitor]         > Error while evaluating property 'compilerOptions.jvmTarget' of task ':falconeta-capacitor-wifi-connect:compileDebugKotlin'.
[capacitor]         > Failed to calculate the value of property 'jvmTarget'.
[capacitor]         > Unknown Kotlin JVM target: 20
[capacitor]         
[capacitor]         * Try:
[capacitor]         > Run with --stacktrace option to get the stack trace.
[capacitor]         > Run with --info or --debug option to get more log output.
[capacitor]         > Run with --scan to get full insights.
[capacitor]         
[capacitor]         * Get more help at https://help.gradle.org
[capacitor]         
[capacitor]         BUILD FAILED in 3s
[capacitor]         230 actionable tasks: 33 executed, 197 up-to-date
[capacitor]         
[ERROR] An error occurred while running subprocess capacitor.
        
        capacitor run android --target emulator-5554 exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
```

I hope you have some clue of how to solve this. As I said, running from Android Studio to my device works fine, but that way I can't get live reload feature from Capacitor. 

Thanks in advance.

**Comment by falconeta** [comment]
Hi @kalanda, first of all check the grade wrapper version (should be >=8), do you use capacitor 5?

**Comment by kalanda** [comment]
> Hi @kalanda, first of all check the grade wrapper version (should be >=8), do you use capacitor 5?

Yep @falconeta , I'm using Capacitor 5.4.1 and Gradle 8.0.2. 

```
./gradlew -v

------------------------------------------------------------
Gradle 8.0.2
------------------------------------------------------------

Build time:   2023-03-03 16:41:37 UTC
Revision:     7d6581558e226a580d91d399f7dfb9e3095c2b1d

Kotlin:       1.8.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          20.0.1 (Homebrew 20.0.1)
OS:           Mac OS X 13.5.2 aarch64
```

**Comment by falconeta** [comment]
Check also the JDK version linked in JAVA_HOME (should be 17).

**Comment by kalanda** [comment]
> Check also the JDK version linked in JAVA_HOME (should be 17).

Seems because of that. I follow this instructions after your reply and it works: https://capacitorjs.com/docs/android/troubleshooting#error-unable-to-locate-a-java-runtime

Again, thanks a lot for your work and help 😄
