### ISSUE TITLE
Auto reconnect to previous network

### ISSUE THREAD

**Issue by jessedewild** [falconeta/capacitor-wifi-connect#13]
Hello,
I am using the plugin to connect to a hotspot that does not have an internet connection.
When the connection is lost, my phone does not automatically reconnect to the previous network.

**Comment by falconeta** [comment]
Hi @jessedewild, i don't understand the problem... what do you mean for previous network (the hotspot without internet connection or another network)? What do you mean with "connection is lost" (device is disconnected to the  hotspot without internet connection)?
which platform have this behavior (ios, android, both)?
