### ISSUE TITLE
Add import example in README

### ISSUE THREAD

**Issue by Ismaele-silla** [falconeta/capacitor-wifi-connect#14]
Hi! Sorry for the annoying request, but could you please add an import example in the readme file? 
I used this format in my project:
`import { CapacitorWifiConnect } from "@falconeta/capacitor-wifi-connect";`
...but it took me a while to figure out how to use the functions within the package. Was there a better/obvious way to import them I couldn't see?

**Comment by falconeta** [comment]
Hi @Ismaele-silla, thank you for your feedback and sorry for delay. Yes, I will describe better the import in the README. Anyway your import is correct 😉

**Comment by Ismaele-silla** [comment]
Thank you so much!
