### ISSUE TITLE
iOS can't connect to WIFI if there is not already an active connection

### ISSUE THREAD

**Issue by okaay3D** [falconeta/capacitor-wifi-connect#15]
Hi, thank you for your work on this plugin. This may be a silly question, but have you ever tried to connect to a network with an iPhone when it is not currently connected to any other network? The system's WIFI settings itself is turned on, but the device is not currently connected to a network.

When I call `secureConnect`, there is not even a system dialogue asking the user if they want to connect to a network. The plugin immediately returns status code `-4` and if the iPhone is currently connected to a WIFI network, the dialogue is displayed. In XCode I have configured my application to have the capabilities/entitlements `com.apple.developer.networking.HotspotConfiguration` and `com.apple.developer.networking.wifi-info`.

I have tried to debug the problem and think there is something wrong with the `func runIsWifiBlock` https://github.com/falconeta/capacitor-wifi-connect/blob/52dd1ef96d18d9bc54660bb35336887cbfc92f54/ios/Plugin/CapacitorWifiConnect.swift#L67

I'm not familiar with Swift or iOS development, so I can't suggest a fix at the moment.

I used the following code to test the connection:
```typescript
  async connect(ssid: string, password: string): Promise<{ value: ConnectState}> {
    const permissionState = await CapacitorWifiConnect.checkPermission();

    if (permissionState.value === 'prompt') {
      await CapacitorWifiConnect.requestPermission();
    }

    if (permissionState.value === 'denied') {
      return Promise.reject(new Error('wifi permission denied'));
    }

    return CapacitorWifiConnect.secureConnect({
      ssid,
      password,
      saveNetwork: false,
      isWep: false,
    });
  }
```

Just to test, I removed the following lines of code from the `func execConnect` to see if iOS can then connect to a network. It actually works, but I assume that this check is there for a reason.
https://github.com/falconeta/capacitor-wifi-connect/blob/52dd1ef96d18d9bc54660bb35336887cbfc92f54/ios/Plugin/CapacitorWifiConnect.swift#L263-L264

Please let me know if I can provide any further information.

**Comment by falconeta** [comment]
Hi @okaay3D, thank you very much for the report, I will check it out and get back to you with feedback as soon as possible
