### ISSUE TITLE
Connecting Capacitor (Android) to Wi-Fi Network getting no results

### ISSUE THREAD

**Issue by jguilhermesl** [falconeta/capacitor-wifi-connect#24]
Description:
I am experiencing an issue when trying to use the library to connect Capacitor (Android) to a Wi-Fi network. I followed the documentation step-by-step, but I am encountering difficulties at the connection stage.

Steps to Reproduce:
1. Followed the installation and configuration guide for the library as described in the official documentation.
 - I created a utility to first try to connect without the password, if it doesn't work, try connecting with the password. 
```
export const wifiConnect = async ({ ssid, password }) => {
  try {
    const data = await CapacitorWifiConnect.connect({
      ssid,
      saveNetwork: true,
    });
    if (data.value === 0) {
      return data;
    }
  } catch (_) {
    const data = await CapacitorWifiConnect.secureConnect({
      ssid,
      password,
      saveNetwork: true,
    });
    if (data.value === 0) {
      return data;
    }
  }

  return { status: -1 };
};
```
2. When attempting to connect to a Wi-Fi network, a modal is displayed correctly asking for the connection.
![Screenshot 2024-07-01 at 10 41 37](https://github.com/falconeta/capacitor-wifi-connect/assets/88175581/61971ec8-de5b-46af-bf0f-991ec174d67b)
4. When clicking "Connect," the device seemingly does not accept/recognize the connection.
5. The device remains disconnected from any network.

Expected Behavior:
The device should successfully connect to the specified Wi-Fi network when "Connect" is clicked.

Actual Behavior:
The device remains unconnected.
![Screenshot 2024-07-01 at 10 45 42](https://github.com/falconeta/capacitor-wifi-connect/assets/88175581/0355f138-c525-4fcd-b2e3-d47822986e29)

**Comment by jguilhermesl** [comment]
@falconeta can you help me?

**Comment by falconeta** [comment]
Hi @jguilhermesl, what android version is used? Do you added the correct permissions inside the manifest? This is a strange issue... any error on logcat?

**Comment by jguilhermesl** [comment]
Hey @falconeta, yes. 
This is my android manifest:
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        android:networkSecurityConfig="@xml/network_security_config">

        <activity
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode"
            android:name=".MainActivity"
            android:label="@string/title_activity_main"
            android:theme="@style/AppTheme.NoActionBarLaunch"
            android:launchMode="singleTask"
            android:exported="true">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

        </activity>

        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths"></meta-data>
        </provider>
    </application>

    <!-- Permissions -->

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
</manifest>
```

I'm using these versions:
```
inSdkVersion = 22
compileSdkVersion = 34
targetSdkVersion = 34
```

**Comment by jguilhermesl** [comment]
I'm not receiving errors at logs @falconeta

**Comment by jguilhermesl** [comment]
Hey @falconeta, any ideas?

**Comment by falconeta** [comment]
Can you share: 
Device model
Android version
Native log session

With this info maybe I can reproduce your situation

**Comment by jguilhermesl** [comment]
@falconeta I'm using Android Studio to emulate.

The device is `10.1  WXGA (Tablet) API 33 (emulator) (10.1_WXGA_Tablet_API_33)`
The android version is 13

What is the native log session?

**Comment by falconeta** [comment]
https://developer.android.com/studio/debug/logcat

**Comment by falconeta** [comment]
@jguilhermesl I will try on an emulator, but this plugin works best when tested on a real device. 
The emulator inherits the wifi state from the PC and changing the SSID is equivalent to changing the SSID on the PC. 

Do a test on a real device ;)
