### ISSUE TITLE
Get available Wi-Fi networks list

### ISSUE THREAD

**Issue by Dipeshjayswal** [falconeta/capacitor-wifi-connect#26]
I am using the @falconeta/capacitor-wifi-connect plugin in my Ionic Capacitor project. I need a way to get a list of available Wi-Fi networks, but looks link the this plugin is not providing. Can you please help me through to get the Wi-Fi list available.
 
I'm developing the feature for Platform(s): Android, iOS
 
Thank you!

**Comment by falconeta** [comment]
Hi @Dipeshjayswal, you can use getSSIDs() (https://github.com/falconeta/capacitor-wifi-connect?tab=readme-ov-file#getssids), this methods works only for Android, iOS does not expose any API to discover a list of available WI-FI :(

**Comment by Dipeshjayswal** [comment]
Okay, Thank you 👍
