### ISSUE TITLE
Add android permissions to plugins AndroidManifest.xml

### ISSUE THREAD

**Issue by AE1NS** [falconeta/capacitor-wifi-connect#3]
What do you think about adding the needed permissions to https://github.com/falconeta/capacitor-wifi-connect/blob/main/android/src/main/AndroidManifest.xml (like https://github.com/ionic-team/capacitor-plugins/blob/main/network/android/src/main/AndroidManifest.xml) because it automatically gets merged with the project.

**Comment by falconeta** [comment]
@AE1NS  thank you for the good advice, i will try to introduce it on next release!
